version: 2.0
jobs:
  build_resume:
    docker:
      - image: circleci/python:2.7.15-stretch-browsers
    working_directory: ~/resume
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build Resume
          command: docker build -t artifacts .

workflows:
  version: 2
  commit:
    jobs:
      - build_resume